



WIDTH = 240
HEIGHT = 180
GAME_WIDTH = WIDTH - 10

ICON_SPACER = 15
ICON_HEIGHT = 5
SPAWN_RATE = 100
SOLDIER_SPAWN = 250
TANK_SPAWN = 200

BUILDING_WIDTH = 8
BUILDING_HEIGHT = 11
BUILDING_AREA = BUILDING_WIDTH * BUILDING_HEIGHT
BUILD_RATE = 10

PLAYER_1 = 10
SOLDIER_COLOUR = 9
NEUTRAL = 4

NEUTRAL = 13

ORE_COLOUR = 2
CURSOR_COLOUR = 7
MENU_COLOUR = PLAYER_1
WARNING_COLOUR = 8
BUILDING_COLOUR = 7
ICON_COLOUR = 9
BUILDING_SITE_COLOUR = 5
BUILD_COLOUR = 14
MINE_COLOUR = 2
IDLE_COLOUR = PLAYER_1
SELECT_COLOUR = 5
ATTACK_COLOUR = 8
COMMAND_COLOUR = 3
DYING_COLOUR = 1

PLAYERS = {PLAYER_1:1}

HOME_BUILD_TIME = 5
MINE_BUILD_TIME = 1
SOLDIER_BUILD_TIME = 40
GENERATOR_BUILD_TIME = 40
FACTORY_BUILD_TIME = 80

MAX_SCROLL_SPEED = 5

HOME_COST = 5
MINE_COST = 5
GENERATOR_COST = 10
FACTORY_COST = 20
BARRACKS_COST = 30

BIT_LIMIT = 1000
BUILDING_LIMIT = 100
ORE_LIMIT = 999
ENERGY_LIMIT = 100

BARRACKS_QUEUE_MAX = 20

FACTORY_QUEUE_MAX = 30



LIMITS = [BIT_LIMIT, BUILDING_LIMIT, ORE_LIMIT, ENERGY_LIMIT]

global id_count
id_count = 0

global viewport
viewport = {'x': 0, 'y': 0}
